const express = require('express')
const router = express.Router()

const { authenticated, authenticatedAdmin } = require('../middlewares/auth-handler')

const root = require('./root')
const admin = require('./modules/admin')
const signUp = require('./signup')
const signIn = require('./signin')
const logOut = require('./logout')
const users = require('./users')
const likes = require('./likes')
const comments = require('./comments')
const favorites = require('./favorites')
const restaurant = require('./restaurant')
const restaurants = require('./restaurants')

router.use('/', root)
router.use('/admin', authenticatedAdmin, admin)
router.use('/signup', signUp)
router.use('/signin', signIn)
router.use('/logout', logOut)
router.use('/users', authenticated, users)
router.use('/likes', authenticated, likes)
router.use('/comments', authenticated, comments)
router.use('/favorites', authenticated, favorites)
router.use('/restaurant', authenticated, restaurant)
router.use('/restaurants', authenticated, restaurants)

module.exports = router
