const express = require('express')
const router = express.Router()

const { authenticated, authenticatedAdmin } = require('../middlewares/auth-handler')
const { generalErrorHandler } = require('../middlewares/error-handler')

const apis = require('./apis')
const root = require('./pages/root')
const signUp = require('./pages/signup')
const signIn = require('./pages/signin')
const logOut = require('./pages/logout')
const admin = require('./pages/modules/admin')
const users = require('./pages/users')
const likes = require('./pages/likes')
const comments = require('./pages/comments')
const favorites = require('./pages/favorites')
const following = require('./pages/following')
const restaurant = require('./pages/restaurant')
const restaurants = require('./pages/restaurants')

router.use('/api', apis)
router.use('/signup', signUp)
router.use('/signin', signIn)
router.use('/logout', logOut)
router.use('/admin', authenticatedAdmin, admin)
router.use('/users', authenticated, users)
router.use('/likes', authenticated, likes)
router.use('/comments', authenticated, comments)
router.use('/favorites', authenticated, favorites)
router.use('/following', authenticated, following)
router.use('/restaurant', authenticated, restaurant)
router.use('/restaurants', authenticated, restaurants)
router.use('/', root)
router.use('/', generalErrorHandler)

module.exports = router
